from enum import StrEnum

class CookieKey(StrEnum):
    SESSION_ID = "session_id"

class ErrorCode(StrEnum):
    WRONG_LOGIN_DATA = "WRONG_LOGIN_DATA"
    WRONG_REGISTER_DATA = "WRONG_REGISTER_DATA"
    UNAUTHORIZED = "UNAUTHORIZED"
    AUTHORIZED = "AUTHORIZED"
    USER_DOESNT_EXIST = "USER_DOESNT_EXIST"
    INVALID_COOKIE_VALUE = "INVALID_COOKIE_VALUE"
    LANGUAGE_DOESNT_EXIST = "LANGUAGE_DOESNT_EXIST"
