name: Backend Jobs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: NGGYU
          POSTGRES_PASSWORD: NGLYD
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      
      - name: Install klinvo-backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Alembic migrations
        env:
          SECRET_KEY: TGIF
          COOKIE_KEY: LFN
          FRONTEND_URL: http://localhost:5173
          COOKIE_SECURE: "False"
          COOKIE_SAMESITE: lax
          DATABASE_URL: postgresql://NGGYU:NGLYD@localhost:5432/test_db
          TEST_DATABASE_URL: postgresql://NGGYU:NGLYD@localhost:5432/test_db
        run: |
          task migrate
      
      - name: Run Pytest
        env:
          SECRET_KEY: TGIF
          COOKIE_KEY: LFN
          FRONTEND_URL: http://localhost:5173
          COOKIE_SECURE: "False"
          COOKIE_SAMESITE: lax
          DATABASE_URL: postgresql://NGGYU:NGLYD@localhost:5432/test_db
          TEST_DATABASE_URL: postgresql://NGGYU:NGLYD@localhost:5432/test_db
        run: |
          task test

  readme-reminder:
    name: Remind to update README after structure changes
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
          
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Check new files and send reminder if README doesn't updated
        run: |
          NEW_FILES=$(git diff --name-only --diff-filter=A origin/${{ github.base_ref }}...HEAD)
          
          ALL_CHANGED_FILES=$(git diff --name-only --diff-filter=M origin/${{ github.base_ref }}...HEAD)

          README_UPDATED=$(echo "$ALL_CHANGED_FILES" | grep -i -x 'README.md' || true)
          README_RU_UPDATED=$(echo "$ALL_CHANGED_FILES" | grep -i -x 'README.RU.md' || true)

          if [ -n "$NEW_FILES" ] && { [ -z "$README_UPDATED" ] || [ -z "$README_RU_UPDATED" ]; }; then
            echo "::warning title=Check README::New files are appeared (relative to the main branch) in this branch, but README.md or README.RU.MD doesn't changed"
            echo "The new files:"
            echo "$NEW_FILES"
          fi
